resolver: ghc-8.10.1

extra-deps:
  - ansi-terminal-0.10.3
  - appar-0.1.8
  - asn1-encoding-0.9.6
  - asn1-parse-0.9.5
  - asn1-types-0.3.4
  - async-2.2.2
  - attoparsec-0.13.2.4
  - auto-update-0.1.6
  - base-orphans-0.8.2
  - basement-0.0.11
  - blaze-builder-0.4.1.0
  - blaze-textual-0.2.1.0
  - bsb-http-chunked-0.0.0.4
  - byteorder-1.0.4
  - call-stack-0.2.0
  - case-insensitive-1.2.1.0
  - cereal-0.5.8.1
  - clock-0.8
  - colour-2.3.5
  - connection-0.3.1
  - cookie-0.4.5
  - cryptonite-0.26
  - data-default-class-0.1.2.0
  - direct-sqlite-2.3.26
  - ghc-paths-0.1.0.12
  - hashable-1.3.0.0
  - hourglass-0.2.12
  - hspec-2.7.1
  - hspec-core-2.7.1
  - hspec-discover-2.7.1
  - hspec-expectations-0.8.2
  - http-client-0.7.0
  - http-client-tls-0.3.5.3
  - http-date-0.0.8
  - http-types-0.12.3
  - http2-2.0.4
  - HUnit-1.6.0.0
  - integer-logarithms-1.0.3
  - iproute-1.7.9
  - memory-0.15.0
  - mime-types-0.1.0.9
  - monad-control-1.0.2.3
  - network-3.1.1.1
  - network-byte-order-0.1.5
  - network-uri-2.6.3.0
  - old-locale-1.0.0.7
  - Only-0.1
  - pem-0.2.4
  - primitive-0.7.0.1
  - psqueues-0.2.7.2
  - QuickCheck-2.14
  - quickcheck-io-0.2.0
  - random-1.1
  - resource-pool-0.2.3.2
  - scientific-0.3.6.2
  - semigroups-0.19.1
  - setenv-0.1.1.3
  - simple-sendfile-0.2.30
  - socks-0.6.1
  - splitmix-0.0.5
  - sqlite-simple-0.4.18.0
  - streaming-commons-0.2.1.2
  - tar-0.5.1.1
  - tf-random-0.5
  - time-manager-0.0.0
  - tls-1.5.4
  - transformers-base-0.4.5.2
  - transformers-compat-0.6.5
  - unix-compat-0.5.2
  - unordered-containers-0.2.10.0
  - vault-0.3.1.4
  - vector-0.12.1.2
  - wai-3.2.2.1
  - warp-3.3.12
  - word8-0.1.3
  - x509-1.7.5
  - x509-store-1.6.7
  - x509-system-1.6.6
  - x509-validation-1.6.11
  - zlib-0.6.2.1

flags:
  transformers-compat:
    five-three: true
