resolver: ghc-8.10.1
extra-deps:
- appar-0.1.8
- asn1-encoding-0.9.6
- asn1-parse-0.9.5
- asn1-types-0.3.4
- async-2.2.2
- attoparsec-0.13.2.4
- auto-update-0.1.6
- basement-0.0.11
- bsb-http-chunked-0.0.0.4
- byteorder-1.0.4
- case-insensitive-1.2.1.0
- cryptonite-0.26
- hashable-1.3.0.0
- hourglass-0.2.12
- http2-2.0.4
- http-date-0.0.8
- http-types-0.12.3
- integer-logarithms-1.0.3
- iproute-1.7.9
- memory-0.15.0
- network-3.1.1.1
- network-byte-order-0.1.5
- pem-0.2.4
- primitive-0.7.0.1
- psqueues-0.2.7.2
- random-1.1
- scientific-0.3.6.2
- semigroups-0.19.1
- simple-sendfile-0.2.30
- streaming-commons-0.2.1.2
- time-manager-0.0.0
- unix-compat-0.5.2
- unordered-containers-0.2.10.0
- vault-0.3.1.4
- wai-3.2.2.1
- warp-3.3.12
- word8-0.1.3
- x509-1.7.5
- zlib-0.6.2.1
