Parameters:

  GitHubPersonalAccessToken:
    Type: String
    Description:
      A GitHub Personal Access Token used to authenticate with their Docker
      registry (docker.pkg.github.com) and pull container images.
    NoEcho: true

  GitHubUsername:
    Type: String
    Description:
      The GitHub username to use for various tasks. This is mostly used to
      avoid repeating yourself.
    Default: tfausak

  ProjectName:
    Type: String
    Description:
      The project name, which is used to name associated resources. Note that
      changing this will probably force replacement on most resources.
    Default: monadoc

Resources:

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html
  DockerCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${ProjectName}-docker-credentials
      Description:
        Credentials used to authenticate with GitHub's Docker registry.
      SecretString: !Sub >
        { "username": "${GitHubUsername}"
        , "password": "${GitHubPersonalAccessToken}"
        }

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${ProjectName}-log-group
      RetentionInDays: 30

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-role-${AWS::Region}
      Description: !Sub
        Role used to launch ECS tasks for the ${ProjectName} project.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
            Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
