conf_forward:
  options_ghc:
    - -XFlexibleContexts
    - -XNoImplicitPrelude
    - -XOverloadedStrings
    - -XScopedTypeVariables
    - -XTypeApplications
conf_layout:
  lconfig_cols: 79
  lconfig_columnAlignMode: { tag: ColumnAlignModeDisabled }
  lconfig_indentPolicy: IndentPolicyLeft
