columns: 79
indent: 2
language_extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - FlexibleContexts
  - NamedFieldPuns
  - NegativeLiterals
  - NoImplicitPrelude
  - NumDecimals
  - NumericUnderscores
  - OverloadedStrings
  - ScopedTypeVariables
  - TypeApplications
steps:
  - imports: { align: none }
  - language_pragmas:
      align: false
      style: compact_line
  - squash: {}
  - trailing_whitespace: {}
