on: push

jobs:

  ci:
    strategy:
      matrix:
        os: [ ubuntu-18.04 ] # TODO , macos-10.15, windows-2019 ]
        ghc: [ '8.10' ]
        cabal: [ '3.2' ]
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - run: echo ${{ github.sha }}
      - run: echo $GITHUB_SHA
      - uses: actions/checkout@v1
      - run: env
      - run: echo ${{ github.sha }}
      - run: echo $GITHUB_SHA
      - id: setup-haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store  }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-
            ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build --enable-tests --jobs --only-dependencies
      - run: cabal build --enable-tests --jobs
      - run: cabal test --jobs --test-show-details direct
      - run: cabal install --install-method copy --installdir artifacts --jobs
      - uses: actions/upload-artifact@v2
        with:
          path: artifacts/monadoc*
          name: monadoc-${{ matrix.os }}-${{ github.sha }}

  docker:
    needs: ci
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: monadoc-ubuntu-18.04-${{ github.sha }}
          path: docker
      - run: chmod +x docker/monadoc
      - uses: docker/build-push-action@v1
        with:
          username: taylorfausak
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: taylorfausak/monadoc
          tags: ${{ github.sha }}
          path: docker
